# Generated by Django 3.2.8 on 2022-03-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='bid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='store.bid'),
            preserve_default=False,
        ),
    ]
