# Generated by Django 3.2.8 on 2022-03-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_transfer_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_hash',
            field=models.CharField(default='default1', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
