# Generated by Django 3.2.8 on 2021-10-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_lastname_customer_last_name'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (name)
        VALUES ('collection1')
        ""","""
        DELETE FROM store_collection
        WHERE name='collection1'
        """)
    ]
