# Generated by Django 3.2.8 on 2022-02-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
