# Generated by Django 3.2.8 on 2021-12-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_collection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
    ]
