# Generated by Django 3.2.8 on 2021-12-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_collection_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='title',
        ),
    ]
