# Generated by Django 3.2.8 on 2021-12-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
