# Generated by Django 3.2.8 on 2022-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default='public1', max_length=600, unique=True),
            preserve_default=False,
        ),
    ]
