# Generated by Django 3.2.8 on 2022-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='randomString',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
