# Generated by Django 3.2.8 on 2022-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220313_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key_hash',
            field=models.CharField(default='publickeyhash1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
